// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dcutr.proto

// Protobuf Java Version: 3.25.5
package org.peergos.protocol.dcutr.pb;

public final class Dcutr {
  private Dcutr() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HolePunchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.protocol.dcutr.pb.HolePunch)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
     * @return The type.
     */
    org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type getType();

    /**
     * <code>repeated bytes ObsAddrs = 2;</code>
     * @return A list containing the obsAddrs.
     */
    java.util.List<com.google.protobuf.ByteString> getObsAddrsList();
    /**
     * <code>repeated bytes ObsAddrs = 2;</code>
     * @return The count of obsAddrs.
     */
    int getObsAddrsCount();
    /**
     * <code>repeated bytes ObsAddrs = 2;</code>
     * @param index The index of the element to return.
     * @return The obsAddrs at the given index.
     */
    com.google.protobuf.ByteString getObsAddrs(int index);
  }
  /**
   * Protobuf type {@code org.peergos.protocol.dcutr.pb.HolePunch}
   */
  public static final class HolePunch extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.peergos.protocol.dcutr.pb.HolePunch)
      HolePunchOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HolePunch.newBuilder() to construct.
    private HolePunch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HolePunch() {
      type_ = 100;
      obsAddrs_ = emptyList(com.google.protobuf.ByteString.class);
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HolePunch();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.peergos.protocol.dcutr.pb.Dcutr.internal_static_org_peergos_protocol_dcutr_pb_HolePunch_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.peergos.protocol.dcutr.pb.Dcutr.internal_static_org_peergos_protocol_dcutr_pb_HolePunch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.class, org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Builder.class);
    }

    /**
     * Protobuf enum {@code org.peergos.protocol.dcutr.pb.HolePunch.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECT = 100;</code>
       */
      CONNECT(100),
      /**
       * <code>SYNC = 300;</code>
       */
      SYNC(300),
      ;

      /**
       * <code>CONNECT = 100;</code>
       */
      public static final int CONNECT_VALUE = 100;
      /**
       * <code>SYNC = 300;</code>
       */
      public static final int SYNC_VALUE = 300;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 100: return CONNECT;
          case 300: return SYNC;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.peergos.protocol.dcutr.pb.HolePunch.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 100;
    /**
     * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type getType() {
      org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type result = org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type.forNumber(type_);
      return result == null ? org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type.CONNECT : result;
    }

    public static final int OBSADDRS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> obsAddrs_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <code>repeated bytes ObsAddrs = 2;</code>
     * @return A list containing the obsAddrs.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getObsAddrsList() {
      return obsAddrs_;
    }
    /**
     * <code>repeated bytes ObsAddrs = 2;</code>
     * @return The count of obsAddrs.
     */
    public int getObsAddrsCount() {
      return obsAddrs_.size();
    }
    /**
     * <code>repeated bytes ObsAddrs = 2;</code>
     * @param index The index of the element to return.
     * @return The obsAddrs at the given index.
     */
    public com.google.protobuf.ByteString getObsAddrs(int index) {
      return obsAddrs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < obsAddrs_.size(); i++) {
        output.writeBytes(2, obsAddrs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < obsAddrs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(obsAddrs_.get(i));
        }
        size += dataSize;
        size += 1 * getObsAddrsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.peergos.protocol.dcutr.pb.Dcutr.HolePunch)) {
        return super.equals(obj);
      }
      org.peergos.protocol.dcutr.pb.Dcutr.HolePunch other = (org.peergos.protocol.dcutr.pb.Dcutr.HolePunch) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!getObsAddrsList()
          .equals(other.getObsAddrsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (getObsAddrsCount() > 0) {
        hash = (37 * hash) + OBSADDRS_FIELD_NUMBER;
        hash = (53 * hash) + getObsAddrsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.peergos.protocol.dcutr.pb.Dcutr.HolePunch prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.peergos.protocol.dcutr.pb.HolePunch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.protocol.dcutr.pb.HolePunch)
        org.peergos.protocol.dcutr.pb.Dcutr.HolePunchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.peergos.protocol.dcutr.pb.Dcutr.internal_static_org_peergos_protocol_dcutr_pb_HolePunch_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.peergos.protocol.dcutr.pb.Dcutr.internal_static_org_peergos_protocol_dcutr_pb_HolePunch_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.class, org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Builder.class);
      }

      // Construct using org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 100;
        obsAddrs_ = emptyList(com.google.protobuf.ByteString.class);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.peergos.protocol.dcutr.pb.Dcutr.internal_static_org_peergos_protocol_dcutr_pb_HolePunch_descriptor;
      }

      @java.lang.Override
      public org.peergos.protocol.dcutr.pb.Dcutr.HolePunch getDefaultInstanceForType() {
        return org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.getDefaultInstance();
      }

      @java.lang.Override
      public org.peergos.protocol.dcutr.pb.Dcutr.HolePunch build() {
        org.peergos.protocol.dcutr.pb.Dcutr.HolePunch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.peergos.protocol.dcutr.pb.Dcutr.HolePunch buildPartial() {
        org.peergos.protocol.dcutr.pb.Dcutr.HolePunch result = new org.peergos.protocol.dcutr.pb.Dcutr.HolePunch(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.peergos.protocol.dcutr.pb.Dcutr.HolePunch result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          obsAddrs_.makeImmutable();
          result.obsAddrs_ = obsAddrs_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.peergos.protocol.dcutr.pb.Dcutr.HolePunch) {
          return mergeFrom((org.peergos.protocol.dcutr.pb.Dcutr.HolePunch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.peergos.protocol.dcutr.pb.Dcutr.HolePunch other) {
        if (other == org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.obsAddrs_.isEmpty()) {
          if (obsAddrs_.isEmpty()) {
            obsAddrs_ = other.obsAddrs_;
            obsAddrs_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureObsAddrsIsMutable();
            obsAddrs_.addAll(other.obsAddrs_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type tmpValue =
                    org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  type_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 18: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureObsAddrsIsMutable();
                obsAddrs_.add(v);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 100;
      /**
       * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type getType() {
        org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type result = org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type.forNumber(type_);
        return result == null ? org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type.CONNECT : result;
      }
      /**
       * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(org.peergos.protocol.dcutr.pb.Dcutr.HolePunch.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .org.peergos.protocol.dcutr.pb.HolePunch.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 100;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> obsAddrs_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensureObsAddrsIsMutable() {
        if (!obsAddrs_.isModifiable()) {
          obsAddrs_ = makeMutableCopy(obsAddrs_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated bytes ObsAddrs = 2;</code>
       * @return A list containing the obsAddrs.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getObsAddrsList() {
        obsAddrs_.makeImmutable();
        return obsAddrs_;
      }
      /**
       * <code>repeated bytes ObsAddrs = 2;</code>
       * @return The count of obsAddrs.
       */
      public int getObsAddrsCount() {
        return obsAddrs_.size();
      }
      /**
       * <code>repeated bytes ObsAddrs = 2;</code>
       * @param index The index of the element to return.
       * @return The obsAddrs at the given index.
       */
      public com.google.protobuf.ByteString getObsAddrs(int index) {
        return obsAddrs_.get(index);
      }
      /**
       * <code>repeated bytes ObsAddrs = 2;</code>
       * @param index The index to set the value at.
       * @param value The obsAddrs to set.
       * @return This builder for chaining.
       */
      public Builder setObsAddrs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureObsAddrsIsMutable();
        obsAddrs_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ObsAddrs = 2;</code>
       * @param value The obsAddrs to add.
       * @return This builder for chaining.
       */
      public Builder addObsAddrs(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureObsAddrsIsMutable();
        obsAddrs_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ObsAddrs = 2;</code>
       * @param values The obsAddrs to add.
       * @return This builder for chaining.
       */
      public Builder addAllObsAddrs(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureObsAddrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, obsAddrs_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ObsAddrs = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearObsAddrs() {
        obsAddrs_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.peergos.protocol.dcutr.pb.HolePunch)
    }

    // @@protoc_insertion_point(class_scope:org.peergos.protocol.dcutr.pb.HolePunch)
    private static final org.peergos.protocol.dcutr.pb.Dcutr.HolePunch DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.peergos.protocol.dcutr.pb.Dcutr.HolePunch();
    }

    public static org.peergos.protocol.dcutr.pb.Dcutr.HolePunch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HolePunch>
        PARSER = new com.google.protobuf.AbstractParser<HolePunch>() {
      @java.lang.Override
      public HolePunch parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HolePunch> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HolePunch> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.peergos.protocol.dcutr.pb.Dcutr.HolePunch getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_peergos_protocol_dcutr_pb_HolePunch_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_peergos_protocol_dcutr_pb_HolePunch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013dcutr.proto\022\035org.peergos.protocol.dcut" +
      "r.pb\"z\n\tHolePunch\022;\n\004type\030\001 \002(\0162-.org.pe" +
      "ergos.protocol.dcutr.pb.HolePunch.Type\022\020" +
      "\n\010ObsAddrs\030\002 \003(\014\"\036\n\004Type\022\013\n\007CONNECT\020d\022\t\n" +
      "\004SYNC\020\254\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_peergos_protocol_dcutr_pb_HolePunch_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_peergos_protocol_dcutr_pb_HolePunch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_peergos_protocol_dcutr_pb_HolePunch_descriptor,
        new java.lang.String[] { "Type", "ObsAddrs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
