// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipns.proto

package org.peergos.protocol.ipns.pb;

public final class Ipns {
  private Ipns() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IpnsEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.protocol.ipns.pb.IpnsEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes value = 1;</code>
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 1;</code>
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>optional bytes signatureV1 = 2;</code>
     */
    boolean hasSignatureV1();
    /**
     * <code>optional bytes signatureV1 = 2;</code>
     */
    com.google.protobuf.ByteString getSignatureV1();

    /**
     * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     */
    boolean hasValidityType();
    /**
     * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     */
    org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType getValidityType();

    /**
     * <code>optional bytes validity = 4;</code>
     */
    boolean hasValidity();
    /**
     * <code>optional bytes validity = 4;</code>
     */
    com.google.protobuf.ByteString getValidity();

    /**
     * <code>optional uint64 sequence = 5;</code>
     */
    boolean hasSequence();
    /**
     * <code>optional uint64 sequence = 5;</code>
     */
    long getSequence();

    /**
     * <code>optional uint64 ttl = 6;</code>
     */
    boolean hasTtl();
    /**
     * <code>optional uint64 ttl = 6;</code>
     */
    long getTtl();

    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     */
    boolean hasPubKey();
    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     */
    com.google.protobuf.ByteString getPubKey();

    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    boolean hasSignatureV2();
    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    com.google.protobuf.ByteString getSignatureV2();

    /**
     * <code>optional bytes data = 9;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 9;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code org.peergos.protocol.ipns.pb.IpnsEntry}
   */
  public  static final class IpnsEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.peergos.protocol.ipns.pb.IpnsEntry)
      IpnsEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IpnsEntry.newBuilder() to construct.
    private IpnsEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IpnsEntry() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      signatureV1_ = com.google.protobuf.ByteString.EMPTY;
      validityType_ = 0;
      validity_ = com.google.protobuf.ByteString.EMPTY;
      sequence_ = 0L;
      ttl_ = 0L;
      pubKey_ = com.google.protobuf.ByteString.EMPTY;
      signatureV2_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IpnsEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              value_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              signatureV1_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType value = org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                validityType_ = rawValue;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              validity_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sequence_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              ttl_ = input.readUInt64();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              pubKey_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              signatureV2_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.class, org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.Builder.class);
    }

    /**
     * Protobuf enum {@code org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType}
     */
    public enum ValidityType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * setting an EOL says "this record is valid until..."
       * </pre>
       *
       * <code>EOL = 0;</code>
       */
      EOL(0),
      ;

      /**
       * <pre>
       * setting an EOL says "this record is valid until..."
       * </pre>
       *
       * <code>EOL = 0;</code>
       */
      public static final int EOL_VALUE = 0;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValidityType valueOf(int value) {
        return forNumber(value);
      }

      public static ValidityType forNumber(int value) {
        switch (value) {
          case 0: return EOL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValidityType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValidityType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValidityType>() {
              public ValidityType findValueByNumber(int number) {
                return ValidityType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.getDescriptor().getEnumTypes().get(0);
      }

      private static final ValidityType[] VALUES = values();

      public static ValidityType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ValidityType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType)
    }

    private int bitField0_;
    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>optional bytes value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes value = 1;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int SIGNATUREV1_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signatureV1_;
    /**
     * <code>optional bytes signatureV1 = 2;</code>
     */
    public boolean hasSignatureV1() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes signatureV1 = 2;</code>
     */
    public com.google.protobuf.ByteString getSignatureV1() {
      return signatureV1_;
    }

    public static final int VALIDITYTYPE_FIELD_NUMBER = 3;
    private int validityType_;
    /**
     * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     */
    public boolean hasValidityType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
     */
    public org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType getValidityType() {
      @SuppressWarnings("deprecation")
      org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType result = org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType.valueOf(validityType_);
      return result == null ? org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType.EOL : result;
    }

    public static final int VALIDITY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString validity_;
    /**
     * <code>optional bytes validity = 4;</code>
     */
    public boolean hasValidity() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes validity = 4;</code>
     */
    public com.google.protobuf.ByteString getValidity() {
      return validity_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 5;
    private long sequence_;
    /**
     * <code>optional uint64 sequence = 5;</code>
     */
    public boolean hasSequence() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 sequence = 5;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    public static final int TTL_FIELD_NUMBER = 6;
    private long ttl_;
    /**
     * <code>optional uint64 ttl = 6;</code>
     */
    public boolean hasTtl() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 ttl = 6;</code>
     */
    public long getTtl() {
      return ttl_;
    }

    public static final int PUBKEY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString pubKey_;
    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     */
    public boolean hasPubKey() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * in order for nodes to properly validate a record upon receipt, they need the public
     * key associated with it. For old RSA keys, its easiest if we just send this as part of
     * the record itself. For newer ed25519 keys, the public key can be embedded in the
     * peerID, making this field unnecessary.
     * </pre>
     *
     * <code>optional bytes pubKey = 7;</code>
     */
    public com.google.protobuf.ByteString getPubKey() {
      return pubKey_;
    }

    public static final int SIGNATUREV2_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString signatureV2_;
    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    public boolean hasSignatureV2() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    public com.google.protobuf.ByteString getSignatureV2() {
      return signatureV2_;
    }

    public static final int DATA_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 9;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bytes data = 9;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signatureV1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, validityType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, validity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, sequence_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, ttl_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, pubKey_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, signatureV2_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signatureV1_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, validityType_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, validity_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, sequence_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, ttl_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, pubKey_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, signatureV2_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.peergos.protocol.ipns.pb.Ipns.IpnsEntry)) {
        return super.equals(obj);
      }
      org.peergos.protocol.ipns.pb.Ipns.IpnsEntry other = (org.peergos.protocol.ipns.pb.Ipns.IpnsEntry) obj;

      boolean result = true;
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && (hasSignatureV1() == other.hasSignatureV1());
      if (hasSignatureV1()) {
        result = result && getSignatureV1()
            .equals(other.getSignatureV1());
      }
      result = result && (hasValidityType() == other.hasValidityType());
      if (hasValidityType()) {
        result = result && validityType_ == other.validityType_;
      }
      result = result && (hasValidity() == other.hasValidity());
      if (hasValidity()) {
        result = result && getValidity()
            .equals(other.getValidity());
      }
      result = result && (hasSequence() == other.hasSequence());
      if (hasSequence()) {
        result = result && (getSequence()
            == other.getSequence());
      }
      result = result && (hasTtl() == other.hasTtl());
      if (hasTtl()) {
        result = result && (getTtl()
            == other.getTtl());
      }
      result = result && (hasPubKey() == other.hasPubKey());
      if (hasPubKey()) {
        result = result && getPubKey()
            .equals(other.getPubKey());
      }
      result = result && (hasSignatureV2() == other.hasSignatureV2());
      if (hasSignatureV2()) {
        result = result && getSignatureV2()
            .equals(other.getSignatureV2());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      if (hasSignatureV1()) {
        hash = (37 * hash) + SIGNATUREV1_FIELD_NUMBER;
        hash = (53 * hash) + getSignatureV1().hashCode();
      }
      if (hasValidityType()) {
        hash = (37 * hash) + VALIDITYTYPE_FIELD_NUMBER;
        hash = (53 * hash) + validityType_;
      }
      if (hasValidity()) {
        hash = (37 * hash) + VALIDITY_FIELD_NUMBER;
        hash = (53 * hash) + getValidity().hashCode();
      }
      if (hasSequence()) {
        hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSequence());
      }
      if (hasTtl()) {
        hash = (37 * hash) + TTL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTtl());
      }
      if (hasPubKey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubKey().hashCode();
      }
      if (hasSignatureV2()) {
        hash = (37 * hash) + SIGNATUREV2_FIELD_NUMBER;
        hash = (53 * hash) + getSignatureV2().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.peergos.protocol.ipns.pb.Ipns.IpnsEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.peergos.protocol.ipns.pb.IpnsEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.protocol.ipns.pb.IpnsEntry)
        org.peergos.protocol.ipns.pb.Ipns.IpnsEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.class, org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.Builder.class);
      }

      // Construct using org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signatureV1_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        validityType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        validity_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        sequence_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        ttl_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        pubKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        signatureV2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_descriptor;
      }

      @java.lang.Override
      public org.peergos.protocol.ipns.pb.Ipns.IpnsEntry getDefaultInstanceForType() {
        return org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.getDefaultInstance();
      }

      @java.lang.Override
      public org.peergos.protocol.ipns.pb.Ipns.IpnsEntry build() {
        org.peergos.protocol.ipns.pb.Ipns.IpnsEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.peergos.protocol.ipns.pb.Ipns.IpnsEntry buildPartial() {
        org.peergos.protocol.ipns.pb.Ipns.IpnsEntry result = new org.peergos.protocol.ipns.pb.Ipns.IpnsEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signatureV1_ = signatureV1_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.validityType_ = validityType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.validity_ = validity_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sequence_ = sequence_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ttl_ = ttl_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.pubKey_ = pubKey_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.signatureV2_ = signatureV2_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.peergos.protocol.ipns.pb.Ipns.IpnsEntry) {
          return mergeFrom((org.peergos.protocol.ipns.pb.Ipns.IpnsEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.peergos.protocol.ipns.pb.Ipns.IpnsEntry other) {
        if (other == org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasSignatureV1()) {
          setSignatureV1(other.getSignatureV1());
        }
        if (other.hasValidityType()) {
          setValidityType(other.getValidityType());
        }
        if (other.hasValidity()) {
          setValidity(other.getValidity());
        }
        if (other.hasSequence()) {
          setSequence(other.getSequence());
        }
        if (other.hasTtl()) {
          setTtl(other.getTtl());
        }
        if (other.hasPubKey()) {
          setPubKey(other.getPubKey());
        }
        if (other.hasSignatureV2()) {
          setSignatureV2(other.getSignatureV2());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.peergos.protocol.ipns.pb.Ipns.IpnsEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.peergos.protocol.ipns.pb.Ipns.IpnsEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 1;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 1;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 1;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signatureV1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signatureV1 = 2;</code>
       */
      public boolean hasSignatureV1() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes signatureV1 = 2;</code>
       */
      public com.google.protobuf.ByteString getSignatureV1() {
        return signatureV1_;
      }
      /**
       * <code>optional bytes signatureV1 = 2;</code>
       */
      public Builder setSignatureV1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signatureV1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signatureV1 = 2;</code>
       */
      public Builder clearSignatureV1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signatureV1_ = getDefaultInstance().getSignatureV1();
        onChanged();
        return this;
      }

      private int validityType_ = 0;
      /**
       * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       */
      public boolean hasValidityType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       */
      public org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType getValidityType() {
        @SuppressWarnings("deprecation")
        org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType result = org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType.valueOf(validityType_);
        return result == null ? org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType.EOL : result;
      }
      /**
       * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       */
      public Builder setValidityType(org.peergos.protocol.ipns.pb.Ipns.IpnsEntry.ValidityType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        validityType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .org.peergos.protocol.ipns.pb.IpnsEntry.ValidityType validityType = 3;</code>
       */
      public Builder clearValidityType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        validityType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString validity_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes validity = 4;</code>
       */
      public boolean hasValidity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes validity = 4;</code>
       */
      public com.google.protobuf.ByteString getValidity() {
        return validity_;
      }
      /**
       * <code>optional bytes validity = 4;</code>
       */
      public Builder setValidity(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        validity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes validity = 4;</code>
       */
      public Builder clearValidity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        validity_ = getDefaultInstance().getValidity();
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <code>optional uint64 sequence = 5;</code>
       */
      public boolean hasSequence() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 sequence = 5;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <code>optional uint64 sequence = 5;</code>
       */
      public Builder setSequence(long value) {
        bitField0_ |= 0x00000010;
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sequence = 5;</code>
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private long ttl_ ;
      /**
       * <code>optional uint64 ttl = 6;</code>
       */
      public boolean hasTtl() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 ttl = 6;</code>
       */
      public long getTtl() {
        return ttl_;
      }
      /**
       * <code>optional uint64 ttl = 6;</code>
       */
      public Builder setTtl(long value) {
        bitField0_ |= 0x00000020;
        ttl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 ttl = 6;</code>
       */
      public Builder clearTtl() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ttl_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       */
      public boolean hasPubKey() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       */
      public com.google.protobuf.ByteString getPubKey() {
        return pubKey_;
      }
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       */
      public Builder setPubKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        pubKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in order for nodes to properly validate a record upon receipt, they need the public
       * key associated with it. For old RSA keys, its easiest if we just send this as part of
       * the record itself. For newer ed25519 keys, the public key can be embedded in the
       * peerID, making this field unnecessary.
       * </pre>
       *
       * <code>optional bytes pubKey = 7;</code>
       */
      public Builder clearPubKey() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pubKey_ = getDefaultInstance().getPubKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signatureV2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public boolean hasSignatureV2() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public com.google.protobuf.ByteString getSignatureV2() {
        return signatureV2_;
      }
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public Builder setSignatureV2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        signatureV2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public Builder clearSignatureV2() {
        bitField0_ = (bitField0_ & ~0x00000080);
        signatureV2_ = getDefaultInstance().getSignatureV2();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 9;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 9;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000100);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.peergos.protocol.ipns.pb.IpnsEntry)
    }

    // @@protoc_insertion_point(class_scope:org.peergos.protocol.ipns.pb.IpnsEntry)
    private static final org.peergos.protocol.ipns.pb.Ipns.IpnsEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.peergos.protocol.ipns.pb.Ipns.IpnsEntry();
    }

    public static org.peergos.protocol.ipns.pb.Ipns.IpnsEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IpnsEntry>
        PARSER = new com.google.protobuf.AbstractParser<IpnsEntry>() {
      @java.lang.Override
      public IpnsEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IpnsEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IpnsEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IpnsEntry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.peergos.protocol.ipns.pb.Ipns.IpnsEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IpnsSignatureV2CheckerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.peergos.protocol.ipns.pb.IpnsSignatureV2Checker)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes pubKey = 7;</code>
     */
    boolean hasPubKey();
    /**
     * <code>optional bytes pubKey = 7;</code>
     */
    com.google.protobuf.ByteString getPubKey();

    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    boolean hasSignatureV2();
    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    com.google.protobuf.ByteString getSignatureV2();
  }
  /**
   * Protobuf type {@code org.peergos.protocol.ipns.pb.IpnsSignatureV2Checker}
   */
  public  static final class IpnsSignatureV2Checker extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.peergos.protocol.ipns.pb.IpnsSignatureV2Checker)
      IpnsSignatureV2CheckerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IpnsSignatureV2Checker.newBuilder() to construct.
    private IpnsSignatureV2Checker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IpnsSignatureV2Checker() {
      pubKey_ = com.google.protobuf.ByteString.EMPTY;
      signatureV2_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IpnsSignatureV2Checker(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 58: {
              bitField0_ |= 0x00000001;
              pubKey_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000002;
              signatureV2_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker.class, org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker.Builder.class);
    }

    private int bitField0_;
    public static final int PUBKEY_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString pubKey_;
    /**
     * <code>optional bytes pubKey = 7;</code>
     */
    public boolean hasPubKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes pubKey = 7;</code>
     */
    public com.google.protobuf.ByteString getPubKey() {
      return pubKey_;
    }

    public static final int SIGNATUREV2_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString signatureV2_;
    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    public boolean hasSignatureV2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes signatureV2 = 8;</code>
     */
    public com.google.protobuf.ByteString getSignatureV2() {
      return signatureV2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(7, pubKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(8, signatureV2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, pubKey_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, signatureV2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker)) {
        return super.equals(obj);
      }
      org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker other = (org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker) obj;

      boolean result = true;
      result = result && (hasPubKey() == other.hasPubKey());
      if (hasPubKey()) {
        result = result && getPubKey()
            .equals(other.getPubKey());
      }
      result = result && (hasSignatureV2() == other.hasSignatureV2());
      if (hasSignatureV2()) {
        result = result && getSignatureV2()
            .equals(other.getSignatureV2());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPubKey()) {
        hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPubKey().hashCode();
      }
      if (hasSignatureV2()) {
        hash = (37 * hash) + SIGNATUREV2_FIELD_NUMBER;
        hash = (53 * hash) + getSignatureV2().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.peergos.protocol.ipns.pb.IpnsSignatureV2Checker}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.peergos.protocol.ipns.pb.IpnsSignatureV2Checker)
        org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2CheckerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker.class, org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker.Builder.class);
      }

      // Construct using org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pubKey_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        signatureV2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.peergos.protocol.ipns.pb.Ipns.internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_descriptor;
      }

      @java.lang.Override
      public org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker getDefaultInstanceForType() {
        return org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker.getDefaultInstance();
      }

      @java.lang.Override
      public org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker build() {
        org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker buildPartial() {
        org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker result = new org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pubKey_ = pubKey_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signatureV2_ = signatureV2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker) {
          return mergeFrom((org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker other) {
        if (other == org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker.getDefaultInstance()) return this;
        if (other.hasPubKey()) {
          setPubKey(other.getPubKey());
        }
        if (other.hasSignatureV2()) {
          setSignatureV2(other.getSignatureV2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes pubKey = 7;</code>
       */
      public boolean hasPubKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes pubKey = 7;</code>
       */
      public com.google.protobuf.ByteString getPubKey() {
        return pubKey_;
      }
      /**
       * <code>optional bytes pubKey = 7;</code>
       */
      public Builder setPubKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pubKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes pubKey = 7;</code>
       */
      public Builder clearPubKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pubKey_ = getDefaultInstance().getPubKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signatureV2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public boolean hasSignatureV2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public com.google.protobuf.ByteString getSignatureV2() {
        return signatureV2_;
      }
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public Builder setSignatureV2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        signatureV2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signatureV2 = 8;</code>
       */
      public Builder clearSignatureV2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signatureV2_ = getDefaultInstance().getSignatureV2();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.peergos.protocol.ipns.pb.IpnsSignatureV2Checker)
    }

    // @@protoc_insertion_point(class_scope:org.peergos.protocol.ipns.pb.IpnsSignatureV2Checker)
    private static final org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker();
    }

    public static org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<IpnsSignatureV2Checker>
        PARSER = new com.google.protobuf.AbstractParser<IpnsSignatureV2Checker>() {
      @java.lang.Override
      public IpnsSignatureV2Checker parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IpnsSignatureV2Checker(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IpnsSignatureV2Checker> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IpnsSignatureV2Checker> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.peergos.protocol.ipns.pb.Ipns.IpnsSignatureV2Checker getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nipns.proto\022\034org.peergos.protocol.ipns." +
      "pb\"\370\001\n\tIpnsEntry\022\r\n\005value\030\001 \001(\014\022\023\n\013signa" +
      "tureV1\030\002 \001(\014\022J\n\014validityType\030\003 \001(\01624.org" +
      ".peergos.protocol.ipns.pb.IpnsEntry.Vali" +
      "dityType\022\020\n\010validity\030\004 \001(\014\022\020\n\010sequence\030\005" +
      " \001(\004\022\013\n\003ttl\030\006 \001(\004\022\016\n\006pubKey\030\007 \001(\014\022\023\n\013sig" +
      "natureV2\030\010 \001(\014\022\014\n\004data\030\t \001(\014\"\027\n\014Validity" +
      "Type\022\007\n\003EOL\020\000\"=\n\026IpnsSignatureV2Checker\022" +
      "\016\n\006pubKey\030\007 \001(\014\022\023\n\013signatureV2\030\010 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_peergos_protocol_ipns_pb_IpnsEntry_descriptor,
        new java.lang.String[] { "Value", "SignatureV1", "ValidityType", "Validity", "Sequence", "Ttl", "PubKey", "SignatureV2", "Data", });
    internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_peergos_protocol_ipns_pb_IpnsSignatureV2Checker_descriptor,
        new java.lang.String[] { "PubKey", "SignatureV2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
